### ISSUE TITLE
Reason for re-calculating the mask?

### ISSUE THREAD

**Issue by miguelvalente** [sebastianbujwid/zsl_text_imagenet#1]
https://github.com/sebastianbujwid/zsl_text_imagenet/blob/48eb0ee0fa0a5b7fd0ac7c97b1e85bf2c63dd59a/text_encoders/text_encoder.py#L21

Title! Still, why not just get `inputs['attention'_mask]` instead?
Thanks!

**Comment by sebastianbujwid** [comment]
No special reason I'm afraid :/

I believe these should be equivalent but please let me know in case you disagree :)
Thanks!

**Comment by miguelvalente** [comment]
> No special reason I'm afraid :/
> 
> I believe these should be equivalent but please let me know in case you disagree :)
> Thanks!

Just curious!
